FROM nvcr.io/nvidia/pytorch:24.03-py3

COPY --from=carlasim/carla:0.9.15 /home/carla/PythonAPI/carla/dist/carla-0.9.15-py3.7-linux-x86_64.egg /tmp/

# Optional: Verify it's there
RUN ls -lh /tmp && file /tmp/carla-0.9.15-py3.7-linux-x86_64.egg

# Corrected pip install with quoting
RUN pip install --no-deps --upgrade "/tmp/carla-0.9.15-py3.7-linux-x86_64.egg"

COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt || true

WORKDIR /app
