version: '3'

services:
  carla-simulator:
    image: carlasim/carla:0.9.14
    command: ./CarlaUE4.sh -RenderOffScreen -nosound -carla-rpc-port=2000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    privileged: true
    network_mode: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia

  carla-client:
    build:
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - ..:/workspace
    working_dir: /workspace
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    depends_on:
      - carla-simulator
