version: '3.8'

services:
  carla_rl:
    container_name: carla_rl
    image: carla-rl-base
    build:
      context: .
      dockerfile: Dockerfile.base
    runtime: nvidia
    environment:
      - AWS_REGION=us-east-1
      - BUCKET_NAME=${BUCKET_NAME:-my-carla-logs-bucket}
    volumes:
      - ./src:/app              # Mounts your source code for live editing
      - ~/.aws:/root/.aws:ro    # Optional: read-only AWS credentials
    command: >
      bash -c "python train.py"
