services:
  carla-simulator:
    image: carlasim/carla:0.9.15
    command: ./CarlaUE4.sh -RenderOffScreen -nosound
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host
    volumes:
      - carla_python:/home/carla/PythonAPI

  carla-client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.base
    image: docker-carla
    volumes:
      - ..:/workspace
      - carla_python:/home/carla/PythonAPI
    working_dir: /workspace
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONPATH=/home/carla/PythonAPI/carla/dist/carla-0.9.15-py3.7-linux-x86_64.egg
    depends_on:
      - carla-simulator

volumes:
  carla_python: