version: '3'

services:
  carla:
    build:
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - ./src:/app/src  # Mount local src directory into container
    working_dir: /app/src
    environment:
      - BUCKET_NAME=${BUCKET_NAME:-attenfuse-carla-logs-bucket}
    command: bash -c "echo 'Please replace this with your training command' && tail -f /dev/null"
