version: '3'

services:
  carla-simulator:
    image: carlasim/carla:0.9.14
    command: ./CarlaUE4.sh -RenderOffScreen -carla-port=2000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    privileged: true
    network_mode: host
    environment:
      - SDL_VIDEODRIVER=offscreen
      - SDL_HINT_CUDA_DEVICE=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=
    runtime: nvidia

  carla-client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.base
    image: docker-carla
    volumes:
      - ..:/workspace
    working_dir: /workspace
    network_mode: host
    depends_on:
      - carla-simulator